# Redirect with a 301
[[redirects]]
from = "http://chat.nnq.dev"
to = "https://discord.com/invite/PeTqzv5Vp7"

[[redirects]]
from = "https://chat.nnq.dev"
to = "https://discord.com/invite/PeTqzv5Vp7"
